name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
      sha:
        required: true
      fail: 
        default: "ok"

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: echo ${{ github.event.inputs.sha }}
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
        run: |
          sleep 25
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
      - run: "[[ \"${{ github.event.inputs.fail }}\" == \"ok\" ]]"
