name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
      sha:
        required: true
      fail: 
        type: number
        default: "0"

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - run: echo ${{ github.event.inputs.sha }}
      - name: Pause for 25 seconds
        run: |
          sleep 25
      - name: exit
        run: exit ${{ github.event.inputs.code }}
